server:
  port: 8102

knife4j:
  enable: false

spring:
  cloud:
    nacos:
      discovery:
        server-addr: XXXX:8848
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://XXXX:3306/oj_db
    username: XXXX
    password: XXXX
    # Redis 配置
  redis:
    database: 1
    host: XXXX
    port: 6379
    timeout: 5000
    password: XXXX

captcha:
  email:
    from: 没办法<1430119384@qq.com> #换成自己的
    password: xxxxxxxx
    host: smtp.qq.com
    port: 465
    user: 1430119384@qq.com
    expire-time: 60 # 60秒
